[package]
name = "database"
version = "0.1.0"
edition = "2024"

# This is a library crate
[lib]
path = "src/lib.rs"

[dependencies]
sea-orm = "1.1.19"
sea-orm-migration = "1.1.19"
serde = { version = "1.0", features = ["derive"] }

migration = { path = "migration" }
shared = { path = "../shared" }
